# Site settings
title: "Jane Arleth dela Cruz"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings

resume_avatar:                  "true"
resume_name:                    "Jane Arleth dela Cruz"
resume_title:                   "Researcher | Engineer | Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jane.delacruz@obf.ateneo.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+639155061699"
resume_contact_address:         "Quezon City, Philippines"
resume_header_contact_info:     "Quezon City, Philippines• +639155061699 • jane.delacruz@obf.ateneo.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>Jane is a young and bright Master’s of Electronics Engineering graduate who is looking for opportunities in the field of data science and cloud computing. She is versed in open source technologies such as Python and Linux from her courses and internship experiences. Jane is a fast-learner and a problem-solver as she exposed herself to several research areas including ubiquitous computing and ICT convergent systems. 
She is competent being able to work independently and with a team. She is disciplined
and efficient in time management being a member of her school’s varsity team since high school until graduate school</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
